language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - BUILD_TOOL=CMake
        - OS=Linux
      sudo: require
    - os: osx
      osx_image: xcode8
      env:
        - BUILD_TOOL=Xcode
        - OS=OSX
  exclude:
    - compiler: clang

git:
  submodules: false

branches:
  only:
    - master

compiler:
  - clang

before_script:
  # Take care of dependencies.
  - sed -i -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - ./setup.sh
  - >
    if [ "$OS" = "OSX" ]; then
      xcodebuild -configuration Release -target emptyExample \
        -project "third-party/openFrameworks/scripts/templates/osx/emptyExample.xcodeproj"
    else
      # Linux/Ubuntu
      sudo third-party/openFrameworks/scripts/linux/ubuntu/install_dependencies.sh -y
      sed -i '9a\ROOT=`pwd`/third-party/openFrameworks' third-party/openFrameworks/scripts/ci/linux/build.sh
      sudo third-party/openFrameworks/scripts/ci/linux/build.sh
      sudo apt-get -y install doxygen
      sudo apt-get -y install cmake
      sudo apt-get -y install libblas-dev
      # Build GRT
      cd third-party/grt/build
      mkdir -p tmp && cd tmp
      cmake .. -DBUILD_EXAMPLES=OFF
      make
      sudo make install
      cd ../../../../
    fi
  # CMake
  - >
    if [ "$BUILD_TOOL" = "CMake" ]; then
      mkdir build
      cd build
      cmake ..
    fi
script:
  - >
    if [ "$BUILD_TOOL" = "CMake" ]; then
      set -e
      # I am in $ROOT/build folder
      USER_CPP=../Xcode/ESP/src/user.cpp
      EXAMPLES=../Xcode/ESP/src/examples/*
      for f in $EXAMPLES
      do
        name=$(basename "$f")
        echo "Compiling example: $f ..."
        echo "#include \"user.h\"" > $USER_CPP
        echo "#include \"examples/$name\"" >> $USER_CPP
        make
      done
    fi;
  - >
    if [ "$BUILD_TOOL" = "Xcode" ]; then
      xcodebuild -configuration Release -target ESP -project "Xcode/ESP/ESP.xcodeproj"
    fi
cache:
  directories:
    - third-party/openFrameworks/libs
before_deploy:
  if [ "$OS" = "Linux" ]; then
     (cd ../Xcode/ESP/ && doxygen Doxyfile)
  fi;
deploy:
  provider: s3
  access_key_id: AKIAIWOAZT5MLNUB2ZEA
  secret_access_key:
    secure: O2CMV7mv8mWEbHAE3pzmLLuTSikoStJaBmy5kn3Yqm9ugXThefhLgSKegxdyYuZ32Li2ES0Vrc/5x5pArW4yTa3/KXZn8/IHDexZsk95P1b1wUaaF1IwY5CQlttrmlnr6zQHCGKujk4Bwzy1SAgNo3ZKkeLJOpGZIDEWldB098WbhlscF3/9kRZS3dWfNRGh+6ja8s/sPQZUHMvaMLS8eAnNXIFq7ng5nZXSOxkf9gwDdj8Ff0+34VZDhS0usjGabzVvBb6enI+Dz5VVXqdBJRFccMUkynlVNRlT0hEFD0asg4UHKwNa8HvdoUiD2LBKxfIcvaRKkLuK57m4W32lCSOB1T15ynQgxTgEq71Z0c7mZ+WUO2x+O+UrqkqJ0Dopwdwla2dovbfyC3omdcDLA5SPVsS0wc9hxBLqEIbBb1og+TgLVhsx6UuDo+QIRs3pWwcZlBBEVLwZYw8yAXCRlLZO8pHNj4PBdEdOHKwwk5OGoJRt0c5ZuK0rxVRGxwANZuzoV7Erl2FV4ryVpQBzoa1v+MypCvZVxjhLQSTaoheos8iLG2SvulR710RVYUO59mDLEJr1wlL/anoipcZdsVX3caJFjKjtF543oPTU3oYQvAGTXI8ZV9NR/CCWJW8rMeKBb5XK/F3MF+WbtSA6gZwBPKiOn3ge8DhvjbTW6Yk=
  bucket: esp-doc
  local-dir: Xcode/ESP/doc/html
  acl: public_read
  on:
    repo: damellis/ESP
    branch: auto-doc
